---
title: "508 Compliance"
---

This is development from notes from a Dec 2021 meeting of the NMFS R User Group.

## From past meetings: 
 - 2021-12-07
   - [Recording of R UG Meeting](https://drive.google.com/file/d/1-KQd2sur0l1UxWtvl03smYR9WexdzVXZ/view?usp=sharing)

## Requirements

### The "Big 5" list (“the bare minimum”) 

List from [NOAA library](https://libguides.library.noaa.gov/Section508/CreatingDocs) that will be used by John DeVore for checking assessment reports submitted to the Pacific Fisheries Management Council:

 - **Tagged content:** The PDF is a tagged PDF.  Auto-tagging is acceptable.  If this step is not done, no other elements will pass because they rely on tagging elements. List of Standard PDF tags from Adobe. https://helpx.adobe.com/acrobat/using/editing-document-structure-content-tags.html#standard_pdf_tags 
 - **Bookmarks:** Bookmarks are present on documents over 20 pages and illustrate the structure of the document.  If a Table of Contents is present, bookmarks should reflect this.  
 - **Alternative Text:** Alt text is present for all figures, charts, maps, equations, etc.
 - **Logical reading order:** The reading order of the elements is logical and follows the flow of the document.
 - **Document properties:** Title and language are present. These features are metadata, where Adobe provides resources about creating and editing document metadata. https://helpx.adobe.com/acrobat/using/pdf-properties-metadata.html

Comprehensive list of features of accessible documents
 - correct tags to all text elements
 - structurally correct headings 1-6
 - each paragraph is marked as single paragraph
 - listings marked as (interlaced) lists
 - table headers defined for data tables
 - the documents correct reading sequence can be identified
 - alternative texts is present for charts and images
 - layout graphics and headers and footers are in the background
 - document has the correct language assigned
 - define language changes within the document
 - bookmarks are available for easier navigation
 - security settings are defined such that they don't block assistive technologies, best to not have security at all
 - field labels for all form fields
 - internal and external references are defined (clickable links and indexes)
 - correct assignments of foot notes
 - reading by means of text flow

### What documents need to be Section 508 compliant?

 - Stock assessment reports (examples [here](https://www.pcouncil.org/stock-assessments-star-reports-stat-reports-rebuilding-analyses-terms-of-reference/groundfish-stock-assessment-documents/)) in PDF format (definitely)
 - Background materials for assessment reviews?
 - Websites
   - Can be checked using this tool [ANDI - Accessibility Testing Tool - Install](https://www.ssa.gov/accessibility/andi/help/install.html)
   - GitHub Issue related to work on getting the r4ss HTML viewer compliant: https://github.com/r4ss/r4ss/issues/411

### More info on alternative text

How descriptive should it be? 
Info on alternative text for complex images https://www.w3.org/WAI/tutorials/images/complex/

## Solutions and information

Assorted links to info online
 - Tags
   - Standards for tagging: Implementing PDF standards for Mathematical Publishing: http://web.science.mq.edu.au/~ross/TaggedPDF/PDF-standards-v2.pdf
 - LaTex packages
   - tagpdf: https://ctan.org/pkg/tagpdf
     - [Example with make file](https://github.com/klpn/accpdf) and [pandoc issue](https://github.com/jgm/pandoc/issues/5409) talking about trials and tribulations with this method
    - Example slide deck: https://www.latex-project.org/publications/2019-08-CAR-TUG-tagged-pdf-slides.pdf
    - [pdfx](http://ctan.math.washington.edu/tex-archive/macros/latex/contrib/pdfx/pdfx.pdf), another LaTex package, used on top of tagpdf with an example [here](http://ctan.math.washington.edu/tex-archive/macros/latex/contrib/pdfx/). 
 - Alternative text
   - knitr: github knitr issue 1879 related to alternative text for figures: https://github.com/yihui/knitr/issues/1879
 - Setting Language
   - from StackExchange \usepackage[pdflang={en-US},pdftex]{hyperref}
 - rmarkdown
   - R Markdown Cookbook (focused on HTML): https://bookdown.org/yihui/rmarkdown-cookbook/html-accessibility.html
   - [pdf engine](https://bookdown.org/yihui/rmarkdown/pdf-document.html) - [lualatex](http://www.luatex.org/) using the following code
   - `pdf_document: latex_engine: xelatex`
 - Checkers
   - .pdf
     - Acrobat pro
     - [PAC 3](https://access-for-all.ch/en/pdf-accessibility-checker.html) - Free PDF Accessibility Checker 3 (2017-12-19) hosted by the [Access for all Foundation](https://access4all.ch/blog/) (Zurich, Switzerland)
     - veraPDF
   - .html (Web Content Accessibility Guidelines)
     - ANDI - Accessibility Testing Tool - Install: https://www.ssa.gov/accessibility/andi/help/install.html
     - WAVE: https://wave.webaim.org/extension/

## Resources
 - tinytex:https://yihui.org/tinytex/
 - Bookdown: https://bookdown.org/

## Example Repos:
 - NWFSC:
   - Kelli Johnson, Aaron Berger, Chantel Wetzel, Andi Stephens, and Ian Taylor are all using using markdown, knitr, or latex for stock assessment reports
   - Erin Steiner automated the creation of Economic Data Reports but now that it’s all online with FISHEyE, had planned to write unformatted tech memos to word and let Al Brown (NWFSC Technical Editor) handle the formatting, but would prefer to use Rd or Rmd. https://www.fisheries.noaa.gov/west-coast/science-data/economic-data-collection-reporting 
   - Nick Tolimeri
 - SWFSC:
   - Melissa Monk created the Rmarkdown  Stock Assessment Template used and adapted by many of those listed above: https://github.com/melissamonk-NOAA/StockAssessment_template
 - AFSC:
   - Jim Ianelli is working on this presumably along with the folks to whom he forwarded an email on the subject (including the S&T folks below): Ben Williams, Cole Monnahan, Ingrid Spies
   - Josh London with NMML has a package that does some accessibility stuff but not full 508 compliance (https://github.com/jmlondon/uswebr) - will be presented via August 13th FIT meeting (contact Corinne Bassin to attend)
S&T National Modeling Team 
   - Christine Stawitz and Corinne Bassin are thinking about this stuff on a national level and across assessment platforms
 - West Coast Region
   - Stacey Miller is coordinator for the Pacific Whiting/Hake treaty and working with Aaron and Kelli (above) and their Canadian counterparts to make all documents posted to the regional website compliant
 - NEFSC
   - Dan Hennen hired a contractor (Tom Price) to make their reports 508 compliant - sounds like they have a working model and are working on creating a package (pending funding?): https://tug.org/tug2020/preprints/Price-Moore-AccessibleTikZ-slides.pdf
   - Andy Beet (EDAB) has been working on making markdown/rmarkdown docs 508 compliant. Focus has been on alt text for images. Many documents (markdown/Rmarkdown) created in EDAB have many images. Converting to word via a reference doc, then to pdf solves the alt text problem (But it’s an ugly process)
 - Other
   - Rmarkdown/latex combination with source code and data for Bering Sea pollock: https://github.com/afsc-assessments/EBSpollock
   - Assessment template (very minimal and I am working on updating it with the latest commits so give me a week) but creates a tagged pdf with alt text github.com/nwfsc-assess/sa4ss
